buyer/urls.py
from django.urls import path
from buyer import views

app_name = 'buyer'

urlpatterns=[
    # path('buyerapp/',views.buyerapp,name='buyerapp'),
    path('',views.buyerapp,name='buyerapp'),
    path('proddetails/<int:id>/',views.proddetails,name ='proddetails'),
    path('cartitems/',views.cartitems,name='cartitems'),
    path('removecart/<int:id>/',views.removecart,name='removecart'),
    path('buyitems/<int:id>/',views.buyitems,name='buyitems'),
    path('addDeliveryDetails/<int:id>/',views.addDeliveryDetails,name='addDeliveryDetails'),
    path('history/',views.history,name='history'),
    path('order/',views.order,name='order'),
    path('notification/',views.notification,name='notification'),
    path('buyerprofile/',views.buyerprofile,name='buyerprofile'),
    path('addressform/',views.addAddress,name='addAddress'),
    path('checkout/<int:id>/',views.checkout,name='checkout'),
    path('buyallproduct/',views.buyallproduct,name='buyallproduct'),
    path('checkoutallprod/',views.checkoutallprod,name='checkoutallprod'),

    path('search/',views.searchView,name='search'),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.homepage),
    path('register/',views.register,name='register'),
    path('login_call/',views.login_call,name='login'),
    path('logout_call/',views.logout_call,name='logout'),
    # path('buyer/',include("buyer.urls")),
    path('',include("buyer.urls")),
    path('seller/',include("seller.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from seller import views

app_name = 'seller'

urlpatterns=[
    path('sellerapp/',views.sellerapp),
    path('addproduct/',views.addproduct),
    path('addcategory/',views.addcategory),
    path('addedproduct/',views.addedproduct),
    path('modifyproduct/<int:id>/',views.modifyproduct,name='modifyproduct'),
    path('sellernotifications/',views.sellernotifications),
    path('createnotifications/',views.createnotifications),
    path('sellerorders/',views.sellerorders),
    path('sellershippcall/<int:id>',views.sellershippcall,name = 'sellershippcall'),
]

templates/addedproduct.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block navigation %}

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Ecommerce App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/seller/sellerapp/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addproduct/">Add Product</a>
          </li>
					<li class="nav-item">
            <a class="nav-link" href="/seller/addcategory/">Add Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addedproduct/">Added Products</a>
          </li>
					<li class="nav-item">
						<a class="nav-link" href="/seller/sellernotifications/">Notifications</a>
					</li>
					<li>
            <a class="nav-link" href="/seller/sellerorders/">Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout_call/">Logout</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

{% endblock %}

{% block mainblock %}
<br>
<div class="row">
	{% for i in prod %}
	<br>
	<div class="col-md-4 card" style="width: 18rem;">
	  <img class="card-img-top" src="{{ i.product_img.url }}" alt="product img!">
	  <div class="card-body">
	    <h5 class="card-title">{{ i.product_name }}</h5>
	    <p class="card-text">Rs {{ i.product_price }}/-</p>
	    <a href="{% url 'seller:modifyproduct' id=i.id %}" class="btn btn-primary">Modify</a>
	  </div>
	</div>
	<br>
	{% endfor %}
</div>
<br>
{% endblock %}

templates/addproduct.html
{% extends 'base.html' %}


{% block navigation %}

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Ecommerce App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/seller/sellerapp/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addproduct/">Add Product</a>
          </li>
					<li class="nav-item">
            <a class="nav-link" href="/seller/addcategory/">Add Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/seller/addedproduct/">Added Products</a>
          </li>
					<li class="nav-item">
						<a class="nav-link" href="/seller/sellernotifications/">Notifications</a>
					</li>
					<li>
            <a class="nav-link" href="/seller/sellerorders/">Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout_call/">Logout</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

{% endblock %}

{% block mainblock %}

	<br><br>
	<h1>Add Product</h1>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<label>Product Name: </label><input type="text" name="pname" class="form-control"><br>

		<label>Description: </label><input type="text" name="desc" class="form-control"><br>

		<label>Price: </label><input type="number" name="price" class="form-control" class="form-control"><br>

		<label>Image: </label><input type="file" name="fil"><br><br>

		<label>Quantity: </label><input type="number" name="qty" class="form-control"><br>

		<label for="">Category:</label><br>
		<select name="catid" class="form-control">
		{% for i in lis %}
			<option value="{{i.cat}}">{{i.cat}}</option>
		{% endfor %}
		</select><br>

		<!--<input type="hidden" name="uname" value="{{request.user}}">-->

		<label>Save Date: </label><br><input type="text" name="sav"><br>

		<label>modified Date: </label><br><input type="text" name="mod"><br>

		<br><input type="submit" value="Add Product" class="btn-primary"><br>

	</form>
	<br><br>
{% endblock %}

templates/addressform.html
{% extends 'base.html' %}

{% block mainblock %}

<!-- uaddid = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
houseno = models.CharField(max_length=20)
    street = models.CharField(max_length = 100)
    ward = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    pin = models.CharField(max_length=6)
    state = models.CharField(max_length=50) -->


<style>
  #id_houseno{
    color: red;
    width: 100px;
    border-radius: 5px;
    border: 1px solid orange;
  }
</style>

<div class="w3-container w3-padding">
  <!-- Start of Checkout Wrapper -->
  <div class="checkout-wrapper pt-10 pb-70">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <main id="primary" class="site-main">
                    <div class="checkout-area">
                        <div class="row">
                            <div class="col-12 col-sm-12 col-md-6 col-lg-7">
                                <div class="checkout-form">
                                    <div class="section-title left-aligned">
                                        <h3>Billing Details</h3>
                                    </div>

                                   

                                    <form action="{% url 'buyer:addAddress' %}"  method="post" enctype="multipart/form-data">
                                    {% csrf_token %}

                                    <div class="form-row mb-3">
                                      <div class="form-group col-12 col-sm-12 col-md-12">
                                          <label for="p_address">Address <span class="text-danger">*</span></label>
                                          <input name="houseno" type="text" class="form-control" id="p_address" required>
                                      </div>
                                  </div>
                                  <div class="form-row mb-3">
                                      <div class="form-group col-12 col-sm-12 col-md-6">
                                          <label for="city_name">City <span class="text-danger">*</span></label>
                                          <input name="city" type="text" class="form-control" id="city_name" required>
                                      </div>
                                      <div class="form-group col-12 col-sm-12 col-md-6">
                                          <label for="province_name">Province <span class="text-danger">*</span></label>
                                          <input type="text" class="form-control" name="state" id="province_name" required>
                                      </div>
                                  </div>
                                  <div class="form-row mb-3">
                                      <div class="form-group col-12 col-sm-12 col-md-6">
                                          <label for="zip_code">Zip Code <span class="text-danger">*</span></label>
                                          <input type="number" class="form-control" name="pin" id="zip_code" required>
                                      </div>
                                   
                                  </div>
                        

                                    
                                        <input type="hidden" name='red' value="{{red}}">
                                        <input type="submit" class="btn btn-secondary dark" value="Save">
                                    </form>           
                                     
                                  </div>

                                            

                                           
                              
                                </div> <!-- end of checkout-form -->
                            </div>
                          
                        </div> <!-- end of row -->
                    </div> <!-- end of checkout-area -->
                </main> <!-- end of #primary -->
            </div>
        </div> <!-- end of row -->
    </div> <!-- end of container -->

</div>
<!-- End of Checkout Wrapper -->



      




</div>
<br>
{% endblock %}


<!--
  <input type="text" name="hno" value="" placeholder="House no." required>
  <input type="text" name="street" value="" placeholder="Street" required>
  <input type="text" name="ward" value="" placeholder="Ward"  required>
  <input type="text" name="city" value="" placeholder="City" required>
  <input type="text" name="dist" value="" placeholder="District" required>
  <input type="text" name="pin" value="" placeholder="Pin" required>
  <input type="text" name="state" value="" placeholder="State"  required>
-->

templates/base.html
<!-- <!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Ecommerce App</title>

  
</head>

<body> -->



  <!-- Navigation -->
  {% block navigation %}
 
  {% include 'navbar.html' %}
 

  {% endblock %}
  
  {% block slider %}

  {% if request.path != '/' %}

  {% else %}
  {% include 'slider.html' %}

  {% endif %}

  
  
  {% endblock %}


  <!-- Page Content -->
 

    <!-- Jumbotron Header -->
    {% block mainblock %}

  

    {% endblock %}




    {% block sellernotifications %}
    {% endblock %}

    {% block createnotifications %}
    {% endblock %}

    {% block sellerorders %}
    {% endblock %}


  <!-- /.container -->



    <!-- footer area start -->  
    <footer>
      <!-- news-letter area start -->
      <div class="newsletter-group">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-lg-12">
                      <div class="newsletter-box">
                          <div class="newsletter-inner">
                              <div class="newsletter-title">
                                  <h3>Sign Up For Newsletters</h3>
                                  <p>Be the First to Know. Sign up for newsletter today</p>
                              </div>
                              <div class="newsletter-box">
                                  <form id="mc-form">
                                      <input type="email" id="mc-email" autocomplete="off" class="email-box" placeholder="enter your email">
                                      <button class="newsletter-btn" type="submit" id="mc-submit">subscribe !</button>
                                  </form>
                              </div>
                          </div>
                          <div class="link-follow">
                              <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
                              <a href="https://plus.google.com/discover"><i class="fa fa-google-plus"></i></a>
                              <a href="https://twitter.com/"><i class="fa fa-twitter"></i></a>
                              <a href="https://www.youtube.com/"><i class="fa fa-youtube"></i></a>
                          </div>
                      </div>
                      <!-- mailchimp-alerts Start -->
                      <div class="mailchimp-alerts">
                          <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                          <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                          <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                      </div><!-- mailchimp-alerts end -->
                  </div>
              </div>
          </div>
      </div>
      <!-- news-letter area end -->
      <!-- footer top area start -->
      <div class="footer-top pt-50 pb-50">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-lg-4 col-md-6 col-sm-6">
                      <div class="footer-single-widget">
                          <div class="widget-title">
                              <div class="footer-logo mb-30">
                                  <a href="index.html">
                                       <img src="assets/img/logo/logo-sinrato.png" alt="">
                                  </a>
                              </div>
                          </div>
                          <div class="widget-body">
                              <p>We are a team of designers and developers that create high quality Magento, Prestashop, Opencart.</p>
                              <div class="payment-method">
                                  <h4>payment</h4>
                                  <img src="assets/img/payment/payment.png" alt="">
                              </div>
                          </div>
                      </div>
                  </div> <!-- single widget end -->
                  <div class="col-lg-2 col-md-6 col-sm-6">
                      <div class="footer-single-widget">
                          <div class="widget-title">
                              <h4>Information</h4>
                          </div>
                          <div class="widget-body">
                              <div class="footer-useful-link">
                                  <ul>
                                      <li><a href="about.html">about us</a></li>
                                      <li><a href="#">Delivery Information</a></li>
                                      <li><a href="#">Privacy Policy</a></li>
                                      <li><a href="#">Terms & Conditions</a></li>
                                      <li><a href="#">Contact Us</a></li>
                                      <li><a href="#">Returns</a></li>
                                      <li><a href="#">Site Map</a></li>
                                  </ul>
                              </div>
                          </div>
                      </div>
                  </div> <!-- single widget end -->
                  <div class="col-lg-3 col-md-6 col-sm-6">
                      <div class="footer-single-widget">
                          <div class="widget-title">
                              <h4>contact us</h4>
                          </div>
                          <div class="widget-body">
                              <div class="footer-useful-link">
                                  <ul>
                                      <li><span>Address:</span> 4710-4890 Breckinridge St,Fayetteville, NC 28311</li>
                                      <li><span>email:</span> support@sinrato.com</li>
                                      <li><span>Call us:</span> <strong>1-1001-234-5678</strong></li>
                                  </ul>
                              </div>
                          </div>
                      </div>
                  </div> <!-- single widget end -->
                  <div class="col-lg-3 col-md-6 col-sm-6">
                      <div class="footer-single-widget">
                          <div class="widget-title">
                              <h4>Our Twitter Feed</h4>
                          </div>
                          <div class="widget-body">
                              <div class="twitter-article">
                                  <div class="twitter-text">
                                      Check out "Alice - Multipurpose Responsive #Magento #Theme" on #Envato by <a href="#">@sinratos</a> #Themeforest <a href="#">https://t.co/DNdhAwzm88</a>
                                      <span class="tweet-time"><i class="fa fa-twitter"></i><a href="#">30 sep</a></span>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div> <!-- single widget end -->
              </div>
          </div>
      </div>
      <!-- footer top area end -->
      <!-- footer bottom area start -->
      <div class="footer-bottom">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-12">
                      <div class="footer-bottom-content">
                          <div class="footer-copyright">
                          <p>Copyright © 2019 <a href="#">sinratos</a>. All Right Reserved</p>
                          </div>
                          <div class="footer-custom-link">
                              <a href="#">Brands</a>
                              <a href="#">Specials</a>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
      <!-- footer bottom area end -->
  </footer>
  <!-- footer area end -->

  <!-- all js include here -->
  <script src="{% static 'sinrato/assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
  <script src="{% static 'sinrato/assets/js/popper.min.js' %}"></script>
  <script src="{% static 'sinrato/assets/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'sinrato/assets/js/plugins.js' %}"></script>
  <script src="{% static 'sinrato/assets/js/ajax-mail.js' %}"></script>
  <script src="{% static 'sinrato/assets/js/main.js' %}"></script>

</body>

</html>

templates/buyallproduct.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block mainblock %}

{% include 'customcss.html' %}

<div class="jumbotron">
  
  <h2><a href="{% url 'buyer:addAddress' %}?next={{request.path}}">Add Address</a>
  </h2>
</div>


<div class="w3-container w3-padding">
  <h3>Review</h3>
  <div class="container">
    <form action="{% url 'buyer:buyallproduct' %} " method="post">
      {% csrf_token %}
      <label for="selone">Address</label><br>
      <select  name="address" style="width:80%;border:2px solid orange;height:35px;" id="selone" required>
        {% for i in address %}
        <option value="{{ i.houseno }} , {{ i.street }} , {{ i.ward }} , {{ i.city }} , {{ i.district }} , {{ i.pin }} , {{ i.state }}">{{ i.houseno }} , {{ i.street }} , {{ i.ward }} , {{ i.city }} , {{ i.district }} , {{ i.pin }} , {{ i.state }}</option>
        {% endfor %}
      </select>
      <br><br><br>
      {% for i in obj %}
        <div class="w3-container w3-padding w3-border" >
          <p><b>{{ i.prodcartid.product_name }}</b></p>
          <img src="{{ i.prodcartid.product_img.url }}" alt="img" height="150" width="150">
          <br>
          <p>Description : {{ i.prodcartid.product_desc }}</p>
          <p>Stock : {{ i.prodcartid.product_avail }} items</p>
          <p>Price : {{ i.prodcartid.product_price }}</p>
          <p>Select Quantity</p>
          <select  name="selc" style="width:80%;border:2px solid orange;height:35px;" id="selone" required>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
        </div>
        <input style="display:none;" type="number" name="ide" value="{{ i.id }}">
        <hr>
      {% endfor %}
      <p>Payment mode</p>
      <select  name="pay" style="width:80%;border:2px solid orange;height:35px;" id="selone" required>
        <option value="Online Wallet">Online Wallet</option>
        <option value="Cash on delivery">Cash on delivery</option>
      </select>
      <br>
      <br>
      <input type="submit" name="sub" value="Reviewed" class="w3-red w3-padding">
      <br><br>
    </form>
  </div>
</div>
{% endblock %}

templates/customcss.html
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<!-- CSS only -->
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.w3-sidebar a {font-family: "Roboto", sans-serif}
body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}


.w3-border{
  border:1px solid yellow !important;
  border-radius: 5px;
}
</style>

templates/prodDeliveryDetails.html
{% extends 'buyerside.html' %}

{% block prodDeliveryDetail %}

<div class="jumbotron">
  
<h2><a href="{% url 'buyer:addAddress' %}?next={{request.path}}">Add Address</a>
</h2>
</div>


<div class="w3-container">
  <h3>Review</h3>
  <div class="w3-container">
    {{ product.product_name }}
    <br>
    <img src="{{ product.product_img.url }}" alt="img" height="130" width="150">
    <p>Description : {{ product.product_desc }}</p>
    <p>Items in stock : {{ product.product_avail }} items</p>
    <p>Retailer : {{ product.added_by_seller }}</p>
    <br>
  </div>

  
  <form  action="{% url 'buyer:addDeliveryDetails' id=idy %}" method="post">
    
    {% csrf_token %}
    <label for="selone">Address</label><br>
    {% if have_add %}
      <select  name="address" style="width:80%;border:2px solid orange;height:35px;" id="selone" required>
        {% for i in address %}
        <option value="{{ i.houseno }} , {{ i.street }} , {{ i.ward }} , {{ i.city }} , {{ i.district }} , {{ i.pin }} , {{ i.state }}">{{ i.houseno }} , {{ i.street }} , {{ i.ward }} , {{ i.city }} , {{ i.district }} , {{ i.pin }} , {{ i.state }}</option>
        {% endfor %}
      </select>

    
    {% endif %}
   
   

    <br><br>
    <label for="seltwo">Quantaty</label><br>
    <select  name="sel" style="width:80%;border:2px solid orange;height:35px;" id="seltwo" required>
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
    </select>
    <br><br>
    <label for="selthree">Payment Option</label><br>
    <select  name="pay" style="width:80%;border:2px solid orange;height:35px;" id="selthree" required>
      <option value="Online Wallet">Online Wallet</option>
      <option value="Cash on delivery">Cash on delivery</option>
    </select>
    <br>
    <br>
    <input type="submit" name="" value="Reviewed" class="w3-red w3-padding">
  </form>
</div>
<br>
{% endblock %}

templates/sinrato_showcart.html
{% extends 'base.html' %}

{% block mainblock %}

<div class="shopping-cart-wrapper pb-70">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <main id="primary" class="site-main">
                    <div class="shopping-cart">
                        <div class="row">
                            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="section-title">
                                    <h3>Shopping Cart</h3>
                                </div>
                            
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <td>Image</td>
                                                    <td>Product Name</td>
                                                   
                                                    <td>Quantity</td>
                                                   
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for i in cart %}
                                                <tr>
                                                    <td>
                                                        <a href="product-details.html"><img src="{{ i.prodcartid.product_img.url }}" alt="Cart Product Image" title="Compete Track Tote" class="img-thumbnail"></a>
                                                    </td>

                                                    <td>
                                                        <a href="product-details.html">{{ i.prodcartid.product_name }}</a>
                                                        <span>Rs {{ i.prodcartid.product_price }}</span>
                                                       
                                                    </td>
=

                                                    <td>
                                                       




                                                        
                                            
                                                   

                                                    

                                              


                                                    <form method="post"  action="{% url 'buyer:removecart' id=i.id %}">
                                                        {% csrf_token %}
                                                        <input type="submit" name="Remove" value="Remove" class="btn btn-danger" style="width:180px;">
                                                      </form>
                                                
                                                            
  
                                                              

                                                        
                                                        
                                                    </td>
                                              
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                             


                                <div class="cart-amount-wrapper">
                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-4 offset-md-8">
                                            <table class="table table-bordered">
                                                <tbody>
                                                    <tr>
                                                        <td>
                                                           
                                                            <a href="{% url 'buyer:buyallproduct' %}"><input type="submit" value="Buy all" name="All" class="w3-button w3-black w3-margin-left" class="btn btn-primary" style="padding:3px;width:180px;"></a>
             
                                                        </td>

                                                    </tr>
                                                    <tr>
                                                        <td><strong>Total:</strong></td>
                                                        <td><span class="color-primary">Rs {{ total }}</span></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                                <div class="cart-button-wrapper d-flex justify-content-between mt-4">
                                    <a href="{%  url 'buyer:buyerapp' %}" class="btn btn-secondary">Continue Shopping</a>
                                    <a href="{% url 'buyer:buyallproduct' %}" class="btn btn-secondary dark align-self-end">Checkout</a>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end of shopping-cart -->
                </main> <!-- end of #primary -->
            </div>
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</div>

{% endblock %}